apiVersion: apps/v1
kind: Deployment
metadata:
  name: secret-redis
spec:
  selector:
    matchLabels:
      app: secret-redis
  replicas: 1
  template:
    metadata:
      labels:
        app: secret-redis
    spec:
      containers:
      - name: secret-redis
        image: redis:latest
        command:
        - redis-server
        - "/redis-master/redis.conf"
        ports:
        - containerPort: 6380
        volumeMounts:
        - name: redis-config-volume
          mountPath: /redis-master
      volumes:
      - name: redis-config-volume
        configMap:
          name: redis-config
          items:
          - key: redis.conf
            path: redis.conf
---
apiVersion: v1
kind: Service
metadata:
  name: secret-redis
spec:
  selector:
    app: secret-redis
  ports:
    - protocol: TCP
      port: 6380
      targetPort: 6380
