apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: statestore
spec:
  type: state.redis
  version: v1
  metadata:
  - name: redisHost
    value: localhost:6380
  - name: redisPassword
    secretKeyRef:
      name: db.password
      value: db.password
auth: 
  secretStore: secretstore
scopes:
 - server
