apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  labels:
    app: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "app"
        dapr.io/config: "tracing"
        dapr.io/volume-mounts: "private-key-config:/var/local/keys"
    spec:
      containers:
      - name: app
        image: marsel888/siuu:app
        ports:
          - containerPort: 3000
        imagePullPolicy: Always
      volumes:
      - name: private-key-config
        configMap:
          name: private-key