apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: statestore
spec:
  type: state.redis
  version: v1
  metadata:
  - name: redisHost
    value: secret-redis.default.svc.cluster.local:6380
  - name: redisPassword
    secretKeyRef:
      name: secretstore
      key: password
auth: 
  secretStore: secretstore
scopes:
 - server